taskmanager/urls.py
from django.conf.urls import url
from django.contrib import admin
import task_app.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', task_app.views.index, name='index'),
    url(r'^signup$', task_app.views.signup, name='signup'),
    url(r'^confirm/(?P<activation_key>\w+)/$', task_app.views.confirm, name='confirm'),
    url(r'^login$', task_app.views.login, name='login'),
    url(r'^logout$', task_app.views.logout, name='logout'),
    url(r'^add_task$', task_app.views.add_task, name='add_task'),
    url(r'^edit_task$', task_app.views.edit_task, name='edit_task'),
    url(r'^complete_task$', task_app.views.complete_task, name='complete_task'),
    url(r'^delete_task$', task_app.views.delete_task, name='delete_task'),
    # url(r'^tag/(?P<tag_name>[-\w\\!@#$%^&*()_=+|:;?/><.~]+)/$', task_app.views.tag, name='tag'),
    # url(r'^done$', task_app.views.done, name='done'),
    # url(r'^not_done$', task_app.views.not_done, name='not_done'),
    # url(r'^all$', task_app.views.all, name='all'),
    # url(r'^deadline_sort$', task_app.views.deadline_sort, name='deadline_sort'),


]

task_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.contrib.auth.models import User, UserManager
from django.db import models

# Create your models here.
from django.utils import timezone


class TaskManager(models.Manager):
    def not_done(self, tag_name, author, sorting_by):
        if tag_name == u"Все теги":
            return self.filter(is_done=False, user=author, is_deleted=False).order_by(sorting_by)
        elif tag_name == u"Без тега":
            return self.filter(tags__isnull=True, is_done=False, user=author, is_deleted=False).order_by(sorting_by)
        else:
            return self.filter(tags__title__exact=tag_name, is_done=False, user=author, is_deleted=False).order_by(sorting_by)

    def done(self, tag_name, author, sorting_by):
        if tag_name == u"Все теги":
            return self.filter(is_done=True, user=author, is_deleted=False).order_by(sorting_by)
        elif tag_name == u"Без тега":
            return self.filter(tags__isnull=True, is_done=True, user=author, is_deleted=False).order_by(sorting_by)
        else:
            return self.filter(tags__title__exact=tag_name, is_done=True, user=author, is_deleted=False).order_by(sorting_by)

    def all_tasks(self, tag_name, author, sorting_by):
        if tag_name == u"Все теги":
            return self.filter(user=author, is_deleted=False).order_by(sorting_by)
        elif tag_name == u"Без тега":
            return self.filter(tags__isnull=True, user=author, is_deleted=False).order_by(sorting_by)
        else:
            return self.filter(tags__title__exact=tag_name, user=author, is_deleted=False).order_by(sorting_by)


    # def deadline_sort(self, author):
    #     return self.filter(is_deleted=False).filter(is_done=False).filter(user=author).order_by('deadline')

    def tag(self, tag_name, author, sorting_by):
        return self.filter(tags__title__exact=tag_name).filter(is_deleted=False).filter(is_done=False). \
            filter(user=author).order_by(sorting_by)

    def no_tag(self, author, sorting_by):
        return self.filter(tags__isnull=True).filter(is_deleted=False).filter(is_done=False). \
            filter(user=author).order_by(sorting_by)



class Tag(models.Model):
    title = models.CharField(max_length=255)


class Task(models.Model):
    title = models.CharField(max_length=255)
    deadline = models.DateField(default=datetime.date.today())
    is_deleted = models.BooleanField(default=False)
    is_done = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=datetime.datetime.now)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey('Profile')
    objects = TaskManager()


class Profile(User):
    activation_key = models.CharField(max_length=40, default='')
    key_expires = models.DateTimeField(default=timezone.localtime(timezone.now()))
    objects = UserManager()

templates/add_task_modal.html
{% load static %}
<!-- Trigger the modal with a button -->
<button type="button" class="btn btn-default btn-lg btn-add-task"
        data-toggle="modal" data-target=".add_task_modal">Добавить задачу
</button>

<!-- Modal -->
<form class="uk-form add_task_form" action="{% url 'add_task' %}" method="POST">
<div class="add_task_modal modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Добавить новую задачу</h3>
            </div>
            <div class="modal-body">

                <!-- Fill the modal body with inputs -->

                    <div class="uk-form-row">
                        {{ form.title }}
{#                        <input type="text" placeholder="Название" class="uk-form-new-task-name">#}
                    </div>


{#                    <div class="uk-form-row">#}
{#                        {{ form.description }}#}
{#                        <textarea rows=10 placeholder="Описание" class="uk-form-new-task-desc"></textarea>#}
{#                    </div>#}
                    <!-- Category and deadline -->
                    <div class="uk-form-row">
                        {{ form.tags }}
{#                        <input type="text" placeholder="Введите теги" class="uk-form-new-task-tag">#}
                    </div>
                    {% for error in form.tags.errors %}
                        <div class=" alert  alert-danger alert-custom" role="alert">
                            <a href="#" class="alert-link">{{ error }}</a>
                        </div>
                    {% endfor %}

                    <div class="uk-form-row">
                        <div class="uk-form-icon">
                            <i class="uk-icon-calendar"></i>
                            {{ form.deadline }}
{#                            <input type="text" class="uk-form-deadline"#}
{#                                   data-uk-datepicker="{minDate: '1',format:'DD.MM.YYYY'}">#}
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default">Добавить</button>
            </div>
        </div>

    </div>
</div>
</form>

{% if enable_modal %}
    <script src={% static "bootstrap/js/jquery.min.js" %}></script>
    <script>
    $(document).ready(function () {
        $(".add_task_modal").modal()
    });
    </script>
{% endif %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Task manager to getting things done">
    <meta name="author" content="Timur Masalimov">

    <title>Task Manager</title>

    <!-- Bootstrap core CSS -->
    <link href={% static "bootstrap/css/bootstrap.min.css" %} rel="stylesheet">

    <!-- Custom styles for this template -->

    <link href={% static "uikit/css/uikit.min.css" %} rel="stylesheet">
    <link href={% static "uikit/css/uikit.docs.min.css" %} rel="stylesheet">

    <link href={% static "my/signup.css" %} rel="stylesheet">
    <link href={% static "semantic/semantic.min.css" %} rel="stylesheet">
    <link href={% static "my/main.css" %} rel="stylesheet">

</head>

<body>
<div class="blog-masthead">
<a class="navbar-brand" href="{% url 'index' %}"><img src="https://cdn2.iconfinder.com/data/icons/justice/512/list_ok_notebook_notation_written-512.png" alt="ToDo">
        </a>
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item
            {% if request.path == '/' %}active{% endif %}" href="{% url 'index' %}">Task</a>
            {% if user.is_authenticated %}
                <a class="blog-nav-item" style="float: right">{{ user.username }}</a>
                <a class="blog-nav-item" style="float: right" href="{% url 'logout' %}">Log out</a>
            {% else %}
                <a class="blog-nav-item
            {% if request.path == '/signup' %}active{% endif %}" href="{% url 'signup' %}">Sign up</a>
                <a class="blog-nav-item
                 {% if request.path == '/login' %}active{% endif %}" href="{% url 'login' %}">Log in</a>
            {% endif %}
        </nav>
    </div>
</div>
{% block content %}
{% endblock %}


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src={% static "bootstrap/js/jquery.min.js" %}></script>
<script src={% static "bootstrap/js/bootstrap.min.js" %}></script>
<script src={% static "uikit/js/uikit.min.js" %}></script>
<script src={% static "uikit/js/components/datepicker.min.js" %}></script>
<script src={% static "my/main.js" %}></script>

</body>
</html>

templates/confirm.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- MAIN PART -->
    {% if expired %}
        <div class="row">
         <div class="col-md-offset-1">
            <h3>Простите, но ключ активации истёк</h3>
         </div>
        </div>
    {% endif %}
    {% if success %}
        <div class="row">
         <div class="col-md-offset-1">
            <h3>Спасибо за регистрацию! <a href="{% url 'login' %}">Залогинтесь</a> и переходите в личный кабинет</h3>
         </div>
        </div>
    {% endif %}

{% endblock %}

templates/index.html
{% extends "base.html" %}


{% block content %}
    <div class="container" xmlns="http://www.w3.org/1999/html">

        <div class="row">
            <div class="col-sm-8 blog-main">
                <div class="blog-header">
                    <h1 class="blog-title">Мои задачи</h1>
                    {% include "add_task_modal.html" %}
                </div>
                <div class="replace-tasks">
                    {% include "task_block.html" %}
                </div>
            </div><!-- /.blog-main -->

            <div class="col-sm-3 col-sm-offset-1 blog-sidebar">

                <div class="sidebar-module sidebar-module-sort">
                    <h2>Сортировка</h2>
                    <ul class="nav nav-pills nav-pills-custom nav-stacked" role="tablist">
                        <li class="active">
                            <a class="sort">По добавлению</a>
                        </li>
                        <li>
                            <a class="sort">По дедлайну</a>
                        </li>
                    </ul>
                </div>


                <div class="sidebar-module sidebar-module-category">
                    <h2>Теги</h2>
                    <ul class="nav nav-pills nav-pills-custom nav-stacked" role="tablist">
                        <li class="active">
                            <a class="tags" id="all_tags_count">
                                <span>Все теги</span>
                                <span class="count_right badge badge-warning">{{ not_done_count }}</span></a>
                        </li>

                        {% for tag in tags %}
                            <li>
                                <a class="tags">
                                    <span class="tag-title">{{ tag.title }}</span>
                                    <span class="count_right badge badge-warning">{{ tag.task_set.count }}</span></a>
                            </li>
                        {% endfor %}

                        <li>
                            <a class="tags" id="none_tags_count">
                                <span>Без тега</span>
                                <span class="count_right badge badge-warning">{{ no_tag_count }}</span></a>
                        </li>
                    </ul>
                </div>

                <div class="sidebar-module sidebar-module-status">
                    <h2>Статус</h2>
                    <ul class="nav nav-pills nav-pills-custom nav-stacked" role="tablist">
                        <li class="active">
                            <a class="status" id="not_done_status_count">
                                <span>Не сделано</span>
                                <span class="count_right badge badge-warning">{{ not_done_count }}</span></a>
                        </li>
                        <li>
                            <a class="status" id="done_status_count">
                                <span>Сделано</span>
                                <span class="count_right badge badge-warning">{{ done_count }}</span></a>
                        </li>
                        <li>
                            <a class="status" id="all_status_count">
                                <span>Все</span>
                                <span class="count_right badge badge-warning">{{ all_count }}</span></a>
                        </li>
                    </ul>
                </div>

            </div><!-- /.blog-sidebar -->

        </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
        {#        <p>Get your things done</p>#}
    </footer>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- MAIN PART -->
<div>
    <div class="container">
        <div class="col-md-6">
            <div id="logbox">
                <form id="login" method="post" action="{% url 'login' %}">
                    <h1>Log in</h1>
                    {{ form.username }}
                    {{ form.password }}

                    {% if text_error != None %}
                        <div class=" alert  alert-danger alert-custom" role="alert">
                            <a href="#" class="alert-link">{{ text_error }}</a>
                        </div>
                    {% endif %}

                    <input type="submit" value="Login!" class="btn btn-default btn-lg btn-block"/>


                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/pagination.html
{% load custom_filter %}
{% if page.paginator.num_pages > 1 %}
<ul class="pagination">
        <li>
            {% if page.has_previous %}
                <a href="?page={{ 1 }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            {% endif %}
        </li>
        {% for i in page|relative_page_list:"4" %}
            {% if i == page.number %}
                <li class="active">
                    <a href="?page={{ i }}">{{ i }}</a>
                </li>
            {% else %}
                <li>
                    <a href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}

        {% endfor %}

        <li>
            {% if page.has_next %}
                <a href="?page={{ page.paginator.num_pages }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
        </li>
</ul>
{% endif %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- MAIN PART -->
    {% if created %}
        <div class="row">
            <div class="col-md-offset-1">
                <h3>Please Confirm Your Email</h3>
            </div>
        </div>

    {% else %}
    <div>
        <div class="container">
            <div class="col-md-6">
                <div id="logbox">
                    <form id="signup" method="post" action="{% url 'signup' %}">
                        <h1>Create an Account</h1>
                        {{ form.username }}
                        {% for error in form.username.errors %}
                            <div class=" alert  alert-danger alert-custom" role="alert">
                                <a href="#" class="alert-link">{{ error }}</a>
                            </div>
                        {% endfor %}

                        {{ form.password }}
                        {{ form.password_repeat }}
                        {% for error in form.password.errors %}
                            <div class=" alert  alert-danger alert-custom" role="alert">
                                <a href="#" class="alert-link">{{ error }}</a>
                            </div>
                        {% endfor %}

                        <input type="submit" value="Sign Up!" class="btn btn-default btn-lg btn-block"/>

                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/single_task.html
<div class="blog-post" data-taskid="{{ task.id }}"
                        data-isdone="{{ task.is_done }}">

    <div class="input-group">
        <span class="input-group-addon">
            <button type="button" class="done-button close" style="float: left"><span class="glyphicon glyphicon-ok"></span></button>
        </span>
        <input class="form-control blog-post-title {% if task.is_done %}title-done{% endif %}" value="{{ task.title }}" readonly="true"
               onfocus="this.value = this.value;">
        <!-- Календарь -->
        <form class="uk-form uk-form-calendar">
            <div class="uk-form-icon">
                <i class="uk-icon-calendar"></i>
                <input type="text" class="uk-form-deadline {% if task.deadline <= date_now %}deadline-over{% endif %}"
                       data-uk-datepicker="{minDate: '1',format:'YYYY-MM-DD'}"
                       value="{{ task.deadline|date:'Y-m-d' }}">
            </div>
        </form>
    </div>

    <p class="blog-post-meta" style="padding-left: 50px">
        {% for t in task.tags.all %}
            <a class="blog-post-meta-link">#{{ t.title }}</a>
        {% endfor %}
    </p>


    <!-- Edit & Delete -->
    <button type="button" class="delete-button close" style="margin-left: 15px;"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
    </button>
    <button type="button" class="edit-button close"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    </button>

</div><!-- /.blog-post -->

templates/tag.html
{% extends "base.html" %}
{% block content %}
    {% for task in tasks %}
        {% include "single_task.html" %}
    {% endfor %}
    {% include "pagination.html" with page=tasks %}
{% endblock %}

{% block tag_block %}
    <ul class="uk-list uk-list-line">
        {% for tag in tags %}
            <li>tag</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/task_block.html
{% for task in tasks %}
    {% include "single_task.html" %}
{% endfor %}
{% include "pagination.html" with page=tasks %}